//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public Libros()
        {
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int LibroID { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
